---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anh Lai.
--- DateTime: 2019/9/12 下午 12:41
---

-- This is loaded before anything else and simply sets up our DEATH_NOTE_API global

local _, DEATH_NOTE = ...
DEATH_NOTE_API = {}