---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anh Lai.
--- DateTime: 2019/9/12 下午 12:31
---
local _, DEATH_NOTE = ...
DEATH_NOTE.CONST = {}

DEATH_NOTE.CONST.VERSION = "0.0.1"

