---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anh Lai.
--- DateTime: 2019/9/12 下午 12:53
---
local _, DEATH_NOTE = ...
DEATH_NOTE.LOCALE = {}

do
    local locale = GetLocale()

    if locale == "zhCN" then

    elseif locale == "zhTW" then

    end
    setmetatable(DEATH_NOTE.LOCALE, {
        __index = function(t, k)
            local v = tostring(k)
            rawset(t, k, v)
            return v
        end,
        __newindex = function(t, k, v)
            error("Cannot write to the locale table")
        end,
    })
end